# This workflow will train a new model and upload it on Rasa


name: New model train and upload

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: Want to train a new model?
        # Default value if no value is explicitly provided
        default: 'yes!'
        # Input has to be provided for the workflow to run
        required: true

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  IMAGE: gce-juicebox-model-trainer

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      # with:
      #   ref: stable

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud components install beta
    # # Get the GKE credentials so we can deploy to the cluster
    # - uses: google-github-actions/get-gke-credentials@v0.2.1
    #   with:
    #     location: ${{ env.GKE_ZONE }}
    #     credentials: ${{ secrets.GKE_SA_KEY }}


    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCE_PROJECT_ID }}
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        export_default_credentials: true

    - name: Set up GPU instance
      run: |-
        gcloud beta compute --quiet --project=juicebox-analytics instances create-with-container gce-juicebox-model-trainer --zone=us-central1-a --machine-type=n1-standard-2 --subnet=default --network-tier=PREMIUM --maintenance-policy=TERMINATE --service-account=819717726903-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --accelerator=type=nvidia-tesla-k80,count=1 --image=debian-10-buster-v20201216 --image-project=debian-cloud --boot-disk-size=10GB --boot-disk-type=pd-standard --boot-disk-device-name=gce-juicebox-model-trainer --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any --container-image "gcr.io/$PROJECT_ID/$IMAGE" --quiet


        
     
    
        
