# This workflow will train a new model and upload it on Rasa


name: New model train and upload

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: Want to train a new model?
        # Default value if no value is explicitly provided
        default: 'yes!'
        # Input has to be provided for the workflow to run
        required: true

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  IMAGE: gce-juicebox-model-trainer

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: List
      run: |-
        bash -c "ls -al /home/runner/work/hostname-app/hostname-app"
      


    
        
     
    
        
